### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by momoDragon** [mrdishant/flutter_geofire#2]
The example app crashes when launch

output:

I/Choreographer( 4807): Skipped 109 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 4807): eglMakeCurrent: 0xde8056c0: ver 2 0 (tinfo 0xde803880)
D/NetworkSecurityConfig( 4807): No Network Security Config specified, using platform default
D/        ( 4807): HostConnection::get() New Host Connection established 0xc89490c0, tid 4834
D/EGL_emulation( 4807): eglMakeCurrent: 0xe652c040: ver 2 0 (tinfo 0xde8030c0)
W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
D/AndroidRuntime( 4807): Shutting down VM
E/AndroidRuntime( 4807): FATAL EXCEPTION: main
E/AndroidRuntime( 4807): Process: mycompany.com.foodpluslifevendor, PID: 4807
E/AndroidRuntime( 4807): java.lang.IllegalArgumentException: Unsupported value: DatabaseError: Permission denied
E/AndroidRuntime( 4807): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/AndroidRuntime( 4807): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/AndroidRuntime( 4807): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
E/AndroidRuntime( 4807): 	at in.appyflow.geofire.GeofirePlugin$4.onGeoQueryError(GeofirePlugin.java:158)
E/AndroidRuntime( 4807): 	at com.firebase.geofire.EventListenerBridge.onGeoQueryError(EventListenerBridge.java:72)
E/AndroidRuntime( 4807): 	at com.firebase.geofire.GeoQuery$6$1.run(GeoQuery.java:231)
E/AndroidRuntime( 4807): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 4807): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4807): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4807): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime( 4807): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4807): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 4807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
I/zygote  ( 4807): Do partial code cache collection, code=29KB, data=23KB
W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
I/zygote  ( 4807): After code cache collection, code=29KB, data=23KB
I/zygote  ( 4807): Increasing code cache capacity to 128KB
W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
Lost connection to device.

**Comment by fliermanrw** [comment]
I have the same error. It seems that somehow permission is denied. Anyone a solution to this problem?

**Comment by fliermanrw** [comment]
> The example app crashes when launch
> 
> output:
> 
> I/Choreographer( 4807): Skipped 109 frames! The application may be doing too much work on its main thread.
> D/EGL_emulation( 4807): eglMakeCurrent: 0xde8056c0: ver 2 0 (tinfo 0xde803880)
> D/NetworkSecurityConfig( 4807): No Network Security Config specified, using platform default
> D/ ( 4807): HostConnection::get() New Host Connection established 0xc89490c0, tid 4834
> D/EGL_emulation( 4807): eglMakeCurrent: 0xe652c040: ver 2 0 (tinfo 0xde8030c0)
> W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
> D/AndroidRuntime( 4807): Shutting down VM
> E/AndroidRuntime( 4807): FATAL EXCEPTION: main
> E/AndroidRuntime( 4807): Process: mycompany.com.foodpluslifevendor, PID: 4807
> E/AndroidRuntime( 4807): java.lang.IllegalArgumentException: Unsupported value: DatabaseError: Permission denied
> E/AndroidRuntime( 4807): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
> E/AndroidRuntime( 4807): at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
> E/AndroidRuntime( 4807): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
> E/AndroidRuntime( 4807): at in.appyflow.geofire.GeofirePlugin$4.onGeoQueryError(GeofirePlugin.java:158)
> E/AndroidRuntime( 4807): at com.firebase.geofire.EventListenerBridge.onGeoQueryError(EventListenerBridge.java:72)
> E/AndroidRuntime( 4807): at com.firebase.geofire.GeoQuery$6$1.run(GeoQuery.java:231)
> E/AndroidRuntime( 4807): at android.os.Handler.handleCallback(Handler.java:790)
> E/AndroidRuntime( 4807): at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime( 4807): at android.os.Looper.loop(Looper.java:164)
> E/AndroidRuntime( 4807): at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/AndroidRuntime( 4807): at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 4807): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/AndroidRuntime( 4807): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
> I/zygote ( 4807): Do partial code cache collection, code=29KB, data=23KB
> W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
> I/zygote ( 4807): After code cache collection, code=29KB, data=23KB
> I/zygote ( 4807): Increasing code cache capacity to 128KB
> W/SyncTree( 4807): Listen at /Sites failed: DatabaseError: Permission denied
> Lost connection to device.

However your problem could be that you want your Reference Path to be /Sites. If you change this to a correct one, does that solve your problem?

**Comment by mrdishant** [comment]
Just add rules in Firebase Realtime Database. its just like permissions to access database.
Your database might be locked or missing sufficient permissions.

For Rules refer : https://firebase.google.com/docs/database/security/
