### ISSUE TITLE
GeoFire.h and Firebase.h not found

### ISSUE THREAD

**Issue by vaisakhjnr** [mrdishant/flutter_geofire#20]
I'm facing the issue when building for iOS.
In GeoFire.m
```
#import "GeoFire.h"
#import "GeoFire+Private.h"
#import "GFGeoHash.h"
#import "GFQuery+Private.h"
#import <Firebase/Firebase.h>
```

The GeoFire.h and Firebase.h are not found by Xcode. I've recently upgraded the firebase plugins to the latest flutter fire version. Any idea why this might be occurring? Been trying all fixes I know of for a week now.

**Comment by mrdishant** [comment]
New Version available. Can you try again?
