### ISSUE TITLE
Null Safety Upgrade - Flutter 2.0

### ISSUE THREAD

**Issue by GrahamDi** [mrdishant/flutter_geofire#21]
Hi,

I would like to know if this package is still actively maintained and if it will be updated to support null safety?

Hoping for a quick response. Thanks.

**Comment by adverthouse** [comment]
Support needed +++  not working in ios as well.

**Comment by debkanchan** [comment]
After the latest commit everything is broken. I had to clone the repo and undo changes and add null safety on my own

**Comment by mrdishant** [comment]
flutter_geofire : 2.0.0 released (Null Safety).

**Comment by marcusrohden** [comment]
Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.

**Comment by GrahamDi** [comment]
Tbh I haven't got to testing it on iOS yet. @mrdishant have you seen this issue?

**Comment by marcuslindemannrohden** [comment]
> Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.

The master from Geofire iOS now references the last version from realtime db.
It should be fixed by now.
I will be testing it later today.

> Tbh I haven't got to testing it on iOS yet. @mrdishant have you seen this issue?

**Comment by prideaux** [comment]
> Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.

Same issue, has anyone found a solution yet?

**Comment by marcusrohden** [comment]
> > Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.
> 
> Same issue, has anyone found a solution yet?

I made it work doing the following:


---- Original iOS Geofire lib (https://github.com/firebase/geofire-objc)

1. Mirror the original git repo from geofire iOS pods and pushed into a private git on my account.
2. Change the podspec from the geofire ios pods lib to the code (the important is the firebase/database version bellow):
```
Pod::Spec.new do |s|
  s.name         = "GeoFire"
  s.version      = "4.2.0"
  s.summary      = "Realtime location queries with Firebase."
  s.homepage     = "https://github.com/firebase/geofire-objc"
  s.license      = { :type => 'MIT', :file => 'LICENSE' }
  s.author       = "Firebase"
  s.source       = { :git => "https://github.com/firebase/geofire-objc.git", :tag => 'v' + s.version.to_s }
  s.ios.deployment_target = '10.0'
  s.requires_arc = true
  s.default_subspec = 'Database'

  s.subspec 'Database' do |db|
    db.ios.dependency 'Firebase/Database', '7.3.0'
    db.ios.dependency 'GeoFire/Utils'
    db.public_header_files = "GeoFire/API/*"
    db.source_files = ["GeoFire/Implementation/*", "GeoFire/API/*"]
    db.frameworks = 'FirebaseDatabase'
  end

  s.subspec 'Utils' do |utils|
    utils.source_files = "GeoFire/Utils/*"
    utils.frameworks = 'CoreLocation'
  end
end
```
3. Commit and push the code above
4. made a custom version tag into my git repo for the commit.



---- My Flutter project

5. on the Podfile from my flutter project added one line to force use of iOS Geofire from my private git instead the original Geofire repository:

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'GeoFire', :git => 'url private git repository', :tag => 'your-custom-tag'
end

**Comment by prideaux** [comment]
> > > Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.
> > 
> > 
> > Same issue, has anyone found a solution yet?
> 
> I made it work doing the following:
> 
> ---- Original iOS Geofire lib (https://github.com/firebase/geofire-objc)
> 
> 1. Mirror the original git repo from geofire iOS pods and pushed into a private git on my account.
> 2. Change the podspec from the geofire ios pods lib to the code (the important is the firebase/database version bellow):
> 
> ```
> Pod::Spec.new do |s|
>   s.name         = "GeoFire"
>   s.version      = "4.2.0"
>   s.summary      = "Realtime location queries with Firebase."
>   s.homepage     = "https://github.com/firebase/geofire-objc"
>   s.license      = { :type => 'MIT', :file => 'LICENSE' }
>   s.author       = "Firebase"
>   s.source       = { :git => "https://github.com/firebase/geofire-objc.git", :tag => 'v' + s.version.to_s }
>   s.ios.deployment_target = '10.0'
>   s.requires_arc = true
>   s.default_subspec = 'Database'
> 
>   s.subspec 'Database' do |db|
>     db.ios.dependency 'Firebase/Database', '7.3.0'
>     db.ios.dependency 'GeoFire/Utils'
>     db.public_header_files = "GeoFire/API/*"
>     db.source_files = ["GeoFire/Implementation/*", "GeoFire/API/*"]
>     db.frameworks = 'FirebaseDatabase'
>   end
> 
>   s.subspec 'Utils' do |utils|
>     utils.source_files = "GeoFire/Utils/*"
>     utils.frameworks = 'CoreLocation'
>   end
> end
> ```
> 
> 1. Commit and push the code above
> 2. made a custom version tag into my git repo for the commit.
> 
> ---- My Flutter project
> 
> 1. on the Podfile from my flutter project added one line to force use of iOS Geofire from my private git instead the original Geofire repository:
> 
> target 'Runner' do
> use_frameworks!
> use_modular_headers!
> 
> flutter_install_all_ios_pods File.dirname(File.realpath(**FILE**))
> pod 'GeoFire', :git => 'url private git repository', :tag => 'your-custom-tag'
> end

Marcus you are a genius!

Followed your instructions and it worked perfectly, I guess we just need to wait for https://github.com/firebase/geofire-objc to update their database version too and this will work fine until then :-D

How long did it take you to figure this out? I owe you some beers!

Thanks!!!

**Comment by marcusrohden** [comment]
> > > > Could you guys run it on iOS? I keep receiving a Pods error stating that it is not compatible with my version from Realtime Database.
> 
> > > 
> 
> > > 
> 
> > > Same issue, has anyone found a solution yet?
> 
> > 
> 
> > I made it work doing the following:
> 
> > 
> 
> > ---- Original iOS Geofire lib (https://github.com/firebase/geofire-objc)
> 
> > 
> 
> > 1. Mirror the original git repo from geofire iOS pods and pushed into a private git on my account.
> 
> > 2. Change the podspec from the geofire ios pods lib to the code (the important is the firebase/database version bellow):
> 
> > 
> 
> > ```
> 
> > Pod::Spec.new do |s|
> 
> >   s.name         = "GeoFire"
> 
> >   s.version      = "4.2.0"
> 
> >   s.summary      = "Realtime location queries with Firebase."
> 
> >   s.homepage     = "https://github.com/firebase/geofire-objc"
> 
> >   s.license      = { :type => 'MIT', :file => 'LICENSE' }
> 
> >   s.author       = "Firebase"
> 
> >   s.source       = { :git => "https://github.com/firebase/geofire-objc.git", :tag => 'v' + s.version.to_s }
> 
> >   s.ios.deployment_target = '10.0'
> 
> >   s.requires_arc = true
> 
> >   s.default_subspec = 'Database'
> 
> > 
> 
> >   s.subspec 'Database' do |db|
> 
> >     db.ios.dependency 'Firebase/Database', '7.3.0'
> 
> >     db.ios.dependency 'GeoFire/Utils'
> 
> >     db.public_header_files = "GeoFire/API/*"
> 
> >     db.source_files = ["GeoFire/Implementation/*", "GeoFire/API/*"]
> 
> >     db.frameworks = 'FirebaseDatabase'
> 
> >   end
> 
> > 
> 
> >   s.subspec 'Utils' do |utils|
> 
> >     utils.source_files = "GeoFire/Utils/*"
> 
> >     utils.frameworks = 'CoreLocation'
> 
> >   end
> 
> > end
> 
> > ```
> 
> > 
> 
> > 1. Commit and push the code above
> 
> > 2. made a custom version tag into my git repo for the commit.
> 
> > 
> 
> > ---- My Flutter project
> 
> > 
> 
> > 1. on the Podfile from my flutter project added one line to force use of iOS Geofire from my private git instead the original Geofire repository:
> 
> > 
> 
> > target 'Runner' do
> 
> > use_frameworks!
> 
> > use_modular_headers!
> 
> > 
> 
> > flutter_install_all_ios_pods File.dirname(File.realpath(**FILE**))
> 
> > pod 'GeoFire', :git => 'url private git repository', :tag => 'your-custom-tag'
> 
> > end
> 
> 
> 
> Marcus you are a genius!
> 
> 
> 
> Followed your instructions and it worked perfectly, I guess we just need to wait for https://github.com/firebase/geofire-objc to update their database version too and this will work fine until then :-D
> 
> 
> 
> How long did it take you to figure this out? I owe you some beers!
> 
> 
> 
> Thanks!!!

Thank you mate! It took me 2 days, but it's not totally my credits, a guy on the geofire ios git pointed me on the right path as he mentioned he could made it work cloning into a private pods and updating the files, I just had to figure out the steps.

Happy coding everybody!

**Comment by mrdishant** [comment]
> pod 'GeoFire', :git => 'url private git repository', :tag => 'your-custom-tag'

You can add the following in PodFile of your app
pod 'GeoFire', :git => 'https://github.com/mrdishant/geofire-objc', :tag => '4.3.0'

Cheers to @marcuslindemannrohden

**Comment by heinzan** [comment]
https://github.com/mrdishant/flutter_geofire/issues/23

Please help.
