### ISSUE TITLE
Stream heading?

### ISSUE THREAD

**Issue by jesussmile** [mrdishant/flutter_geofire#27]
Is it possible to stream heading with geofire. Currently I can stream my latitude longitude and id only.

**Comment by SandaruwanFdo** [comment]
Useful feature. please add heading value for package

**Comment by SandaruwanFdo** [comment]
Is this done? can upgrade plugin now

**Comment by jesussmile** [comment]
You can calculate the direction by comparing your current latitude and longitude with the previous ones. You don't need geofire for that.
