### ISSUE TITLE
Please upgrade to support supports the Android V2 embedding

### ISSUE THREAD

**Issue by TranThienTrong** [mrdishant/flutter_geofire#28]
The plugin `flutter_geofire` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.

**Comment by someshlaheri** [comment]
Please help, I'm facing this same issue. I have tried with all versions but still does not work for me.

Thank you.

**Comment by zakblacki** [comment]
Same issue !

**Comment by KamiTzayig** [comment]
same here ^^

**Comment by danielmintz** [comment]
Same problem here. Just stopped working

**Comment by raissa-goes** [comment]
I have the some problem here. Please upgrade the package.

**Comment by wcosmas** [comment]
Same problem

**Comment by edoardodc** [comment]
Same problem :(

**Comment by mrdishant** [comment]
Hello All

Plugin updated

**Comment by TranThienTrong** [comment]
> Hello All
> 
> Plugin updated

Thanks
