### ISSUE TITLE
Release build failing 

### ISSUE THREAD

**Issue by savinmathew** [mrdishant/flutter_geofire#3]
`flutter build apk`  

command failing with the following error 

> FAILURE:

>  Build failed with an exception.                                
>                                                                         
> * What went wrong:                                                      
> Execution failed for task ':flutter_geofire:verifyReleaseResources'.    
> 

> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/savin/Documents/Development/FlutterProjects/clubme/build/flutter_geofire/intermediates/res/merged/release/values/values.xml:276: error: resource android:attr/fontVariationSettings not found.
  /Users/savin/Documents/Development/FlutterProjects/clubme/build/flutter_geofire/intermediates/res/merged/release/values/values.xml:277: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     

>  Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                         
> * Get more help at https://help.gradle.org                              
>                                                                         
> BUILD FAILED in 1m 10s 

Flutter doctor output

> flutter doctor -v
> [✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-IN)
>     • Flutter version 1.2.1 at /Users/savin/Documents/Development/flutter
>     • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/savin/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 33.1.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] Connected device (1 available)
>     • Mi A1 • 321b263b0604 • android-arm64 • Android 8.1.0 (API 27)
> 
> • No issues found!

**Comment by mrdishant** [comment]
This is a problem with Android build 

Have a look at this StackOverflow Answer 
https://stackoverflow.com/questions/54375194/flutter-android-studio-build-failing

This will. solve the issue.
