### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Database":

### ISSUE THREAD

**Issue by danielmintz** [mrdishant/flutter_geofire#33]
Im getting this issue. Had one similar maybe a year back.  

> !] CocoaPods could not find compatible versions for pod "Firebase/Database":
>   In snapshot (Podfile.lock):
>     Firebase/Database (= 9.4.0)
> 
>   In Podfile:
>     firebase_database (from `.symlinks/plugins/firebase_database/ios`) was resolved to 9.1.2, which depends on
>       Firebase/Database (= 9.4.0)
> 
>     flutter_geofire (from `.symlinks/plugins/flutter_geofire/ios`) was resolved to 0.0.1, which depends on
>       GeoFire (~> 4.0) was resolved to 4.1.0, which depends on
>         Firebase/Database (~> 6.0)
> 
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * changed the constraints of dependency `Firebase/Database` inside your development pod `flutter_geofire`.
>    You should run `pod update Firebase/Database` to apply changes you've made.

I am using 

firebase_core: ^1.21.0
firebase_database: ^9.1.2
flutter_geofire: ^2.0.1

**Comment by ziaulislamzia** [comment]
i am having the same problem with IOS only. works fine on Android.
================================================
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
======================================================

let me know if you got sorted thanks.

**Comment by danielmintz** [comment]
@mrdishant hi there, good morning. Is the package still being maintained? Noticed it has been a while since a release and having a few issues as above. Just wondering whether to hang on or look for an alternative. Kind Regards.

**Comment by sdkysfzai** [comment]
I'm also having this same issue... What to do about this?

**Comment by johnkyony** [comment]
I am having similar issue as well with this plugin , has the issue been resolved yet , or has anyone found a work around

**Comment by abdelrahman-tolba-software-developer** [comment]
just use 
At End Of podfile

pod 'GeoFire', :git => 'https://github.com/abdoelmorap/geofire-objc', :tag => '5.4.0'

**Comment by abeticlairon** [comment]
I tried using @abdoelmorap solution but it still doesn't work. Perhaps the flutter_geofire package is now obsolete. I get the following error:

`
CocoaPods could not find compatible versions for pod "GeoFire":
  In Podfile:
    GeoFire (from `https://github.com/abdoelmorap/geofire-objc`, tag `5.4.0`)

    flutter_geofire (from `.symlinks/plugins/flutter_geofire/ios`) was resolved to 0.0.1, which depends on
      GeoFire (~> 4.0)
`

**Comment by mrdishant** [comment]
Plugin updated.

Check the README to resolve this issue
