### ISSUE TITLE
MIssingPluginException

### ISSUE THREAD

**Issue by shanazainab** [mrdishant/flutter_geofire#5]
E/flutter ( 6014): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method GeoFire.start on channel geofire)

**Comment by Avishaidev** [comment]
same issue (Android)
any update?

**Comment by mrdishant** [comment]
Kindly stop and run again

Reload will not work for new added plugins
