### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by i6x86** [mrdishant/flutter_geofire#6]
[!] Unable to determine Swift version for the following pods:

- `flutter_geofire` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by aloism** [comment]
i am having the same issue, Did you manage to solve this or you had to work out an alternative? if you worked out an alternative please help.

**Comment by i6x86** [comment]
> i am having the same issue, Did you manage to solve this or you had to work out an alternative? if you worked out an alternative please help.


I've started a new project adding all the plugins one by one and everything works fine now. I have no idea what I did wrong but you can give a try to the following:

-  pod update
- Remove ios/Podfile.lock file
- Go to the Podfile file and change it from platform :ios, '9.0' to platform :ios, '11.0'
- Go to the terminal , ios directory and run pod install
- Run the project again.
Hope it helps.

**Comment by kareldebedts** [comment]
https://stackoverflow.com/questions/57747051/flutter-package-build-error-swift-file-not-found
