### ISSUE TITLE
The file reference for "Firebase.xcconfig" is a member of multiple groups ("Support Files" and "Support Files")

### ISSUE THREAD

**Issue by hareshgediya** [mrdishant/flutter_geofire#7]
I will add following pub to my project.
firebase_core: ^0.4.0+9
firebase_auth: ^0.14.0+4
firebase_database: ^3.0.7
flutter_geofire: ^1.0.1

I am facing following error and say failed to build iOS app.
_xcodebuild[3214:31724] warning: The file reference for "Firebase.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project. Only the membership in one of the groups will be preserved (but membership in targets will be unaffected). If you want a reference to the same file in more than one group, please add another reference to the same path._

**Comment by tolgakartal** [comment]
Go to you iOS/.symlinks folder and remove firebase plugin (may not exist)
flutter clean
Delete Podfile.lock
Delete Pods folder
Delete Podfile (I backed up my existing Podfile)
In terminal: pod init
In terminal: pod install
Copied the contents of my previous Podfile into the Podfile generated by the pod init command
pod install
In terminal: flutter run or just flutter build iOS
