### ISSUE TITLE
Error when running this lib on iOS, pod install error

### ISSUE THREAD

**Issue by aloism** [mrdishant/flutter_geofire#9]
I am failing to run my project on iOS due the this library, 
Pod install on iOS folder if producing the following error:
`flutter_geofire` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by kareldebedts** [comment]
https://stackoverflow.com/questions/57747051/flutter-package-build-error-swift-file-not-found
